service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

# Define your functions
functions:
  # A function handler name
  hello:
    # The actual function handler reference
    handler: handler.hello
    # Events list that trigger this handler
    events:
      # Run this function on httpApi on the path / on the method get
      - httpApi:
          path: /
          method: get
